### ISSUE TITLE
incorrect or not handling of errors

### ISSUE THREAD

**Issue by ha1331** [Step7750/CSGOFloat#11]
Just found few servers gone down  with this error:
Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com:443
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

I assume this has to do with not catching specific errors when doing http(s) requests

**Comment by ha1331** [comment]
Looks like it's caused by function `downloadFile` at `lib/utils.js` There seems to be nothing to catch errors and because of that, when  `https.get()` throws, the app dies.
