### ISSUE TITLE
Protobuf Error?

### ISSUE THREAD

**Issue by sneak-it** [Step7750/CSGOFloat#20]
Hello, I went to run this today for the first time, and am receiving an error:

```
user@server:~/csgofloat$ node index.js
info: Updating Game Files...
info: Logging in redacted
/home/user/csgofloat/node_modules/protobufjs/dist/protobuf.js:784
                throw e;
                ^

Error: Parse error at line 1: unexpected '404'
    at Parser.ProtoBuf.DotProto.ParserPrototype.parse (/home/user/csgofloat/node_modules/protobufjs/dist/protobuf.js:779:35)
    at Function.ProtoBuf.DotProto.Parser.parse (/home/user/csgofloat/node_modules/protobufjs/dist/protobuf.js:797:39)
    at Object.ProtoBuf.loadProto (/home/user/csgofloat/node_modules/protobufjs/dist/protobuf.js:5128:59)
    at Object.ProtoBuf.loadProtoFile (/home/user/csgofloat/node_modules/protobufjs/dist/protobuf.js:5174:52)
    at Object.<anonymous> (/home/user/csgofloat/node_modules/csgo/helpers/protos.js:14:10)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

I'd be happy to provide any more information that you require!

**Comment by Step7750** [comment]
This seems to be a `node-csgo` or `node-steam-resources` issue.

You can try running `npm install seishun/node-steam-resources`

**Comment by sneak-it** [comment]
Hmm, no dice unfortunately, attached error log.

[2018-12-13T21_06_00_403Z-debug.log](https://github.com/Step7750/CSGOFloat/files/2677724/2018-12-13T21_06_00_403Z-debug.log)

**Comment by Step7750** [comment]
Yeah, was able to replicate it on a new install, investigating.

**Comment by Step7750** [comment]
Could you please clone the `fix/steam-resources` branch and run `npm install` to see if it works?

**Comment by sneak-it** [comment]
Progress! Seems to just stop after retrieving items_game.txt

[2018-12-13T21_38_01_263Z-debug.log](https://github.com/Step7750/CSGOFloat/files/2677833/2018-12-13T21_38_01_263Z-debug.log)
[log.txt](https://github.com/Step7750/CSGOFloat/files/2677834/log.txt)

**Comment by Step7750** [comment]
Looks like #19 might still be an issue with `node-steam`, there is a manual server list there.

Seems like a fix was put into https://github.com/seishun/node-steam/commit/8f0f68bc244bc02fd38c585bbe956b9546c562a0, but I don't know when a new release will be published.

I might migrate to `node-globaloffensive` and `node-steam-user` given how this has been a recurring issue.
