### ISSUE TITLE
error this.steamClient.disconnect is not a function

### ISSUE THREAD

**Issue by denis-marecky** [Step7750/CSGOFloat#54]
info: Updating Game Files...
info: Logging in loginnamehere
/steambots/csgofloat/lib/bot.js:61
        if (this.steamClient) this.steamClient.disconnect();
                                               ^

TypeError: this.steamClient.disconnect is not a function
    at Bot.logIn (/steambots/csgofloat/lib/bot.js:61:48)
    at BotController.addBot (/steambots/csgofloat/lib/bot_controller.js:14:13)
    at Object.<anonymous> (/steambots/csgofloat/index.js:44:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

**Comment by denis-marecky** [comment]
error only with manual install. Docker works fine

**Comment by Step7750** [comment]
How are you interfacing with the API? Are you simply deploying it or trying to use it in your code?

**Comment by denis-marecky** [comment]
Simply deploying

**Comment by Step7750** [comment]
Could you please detail your installation steps? What version of Node and npm?

I'm not able to reproduce this on Node v12.7.0 and NPM v6.11.2.

If you are running `npm install csgofloat`, could you try cloning the repo manually then running `npm install` in it?

**Comment by Step7750** [comment]
Closing due to no activity
